version: 1.15.{build}.0

os: Visual Studio 2015

environment:
  CoverallsRepoToken:
    secure: t/5ID5XZAyFKZNmgVJIrcs2Ah7Bn1Kr2cmAZcmEbvl/lGHHl6F4sxSLHK89z7I7E

assembly_info:
  patch: true
  file: AssemblyVersion.cs
  assembly_version: "1.15.0.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  project: src\SqlLocalDb.msbuild
  verbosity: minimal

artifacts:
  - path: src\BuildOutput\*.nupkg
  - path: src\BuildOutput\*.zip
  - path: src\TestResults\*\*.coverage

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: GitHub
    tag: "$(APPVEYOR_REPO_TAG_NAME)"
    release: "SQL LocalDB Wrapper $(APPVEYOR_REPO_TAG_NAME)"
    description: "$(GitHubReleaseDescription)"
    auth_token:
      secure: mLFHRaYb30++8z/i4iDEkwLI3XzuAfbdbzyWVsxANtzs2aGWMWMuClfUC+QSU6YF
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    api_key:
      secure: 7xiMOBgPvPg3LrtOPUFfhJJqcCU/fKHWG9WHVDgPnBI74dAd3lgeh1VxL7qjM5R0
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
